dist: trusty
language: node_js
node_js:
  - 'stable'

branches:
  only:
  - master
  - next
  - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules

before_script: npm run lint
after_success: npm run coverage
